### ISSUE TITLE
Unicode errors thrown

### ISSUE THREAD

**Issue by Ryj3l** [OpenBMB/ChatDev#103]
Traceback (most recent call last):
  File "<path_to_tenacity>", line 382, in __call__
    result = fn(*args, **kwargs)
  File "<path_to_utils>", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "<path_to_chat_agent>", line 191, in step
    response = self.model_backend.run(messages=openai_messages)
  File "<path_to_model_backend>", line 69, in run
    response = openai.ChatCompletion.create(*args, **kwargs,
  File "<path_to_openai_chat_completion>", line 25, in create
    return super().create(*args, **kwargs)
  File "<path_to_engine_api_resource>", line 153, in create
    response, _, api_key = requestor.request(
  File "<path_to_api_requestor>", line 288, in request
    result = self.request_raw(
  File "<path_to_api_requestor>", line 596, in request_raw
    result = _thread_context.session.request(
  File "<path_to_requests_session>", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "<path_to_requests_session>", line 703, in send
    r = adapter.send(request, **kwargs)
  File "<path_to_requests_adapters>", line 486, in send
    resp = conn.urlopen(
  File "<path_to_urllib3_connectionpool>", line 790, in urlopen
    response = self._make_request(
  File "<path_to_urllib3_connectionpool>", line 496, in _make_request
    conn.request(
  File "<path_to_urllib3_connection>", line 387, in request
    self.putheader(header, value)
  File "<path_to_urllib3_connection>", line 301, in putheader
    super().putheader(header, *values)
  File "<path_to_http_client>", line 1259, in putheader
    values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode character '\u201c' in position 7: ordinal not in range(256)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<path_to_run>", line 111, in <module>
    chat_chain.execute_chain()
  File "<path_to_chat_chain>", line 160, in execute_chain
    self.execute_step(phase_item)
  File "<path_to_chat_chain>", line 130, in execute_step
    self.chat_env = self.phases[phase].execute(self.chat_env,
  File "<path_to_phase>", line 292, in execute
    self.chatting(chat_env=chat_env,
  File "<path_to_utils>", line 77, in wrapper
    return func(*args, **kwargs)
  File "<path_to_phase>", line 131, in chatting
    assistant_response, user_response = role_play_session.step(input_user_msg, chat_turn_limit == 1)
  File "<path_to_role_playing>", line 242, in step
    assistant_response = self.assistant_agent.step(user_msg_rst)
  File "<path_to_tenacity>", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "<path_to_tenacity>", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "<path_to_tenacity>", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x(hex_address) state=finished raised UnicodeEncodeError>]

**Comment by Ryj3l** [comment]
I'm running my environment as prescribed in the wiki with Conda and Python 3.9 

Any help would be appreciated.

**Comment by mudislandkid** [comment]
Did you manage to get this fixed as I'm running into the same issue. Honda with Python 3.9.18

**Comment by Ryj3l** [comment]
Yes. The problem was actually my powershell version. Once I updated to the latest powershell the issue went away.
