### ISSUE TITLE
ValueError: OpenAI API key not found.

### ISSUE THREAD

**Issue by stjema** [OpenBMB/ChatDev#104]
yes im putting the api key between " and ".
anaconda prompt powershell: set OPENAI_API_KEY="your_OpenAI_API_key"
it doesnt work in cmd.

**console:**
Note that we must ONLY discuss the product modality and do not discuss anything else! Once we all have expressed our opinion(s) and agree with the results of the discussion unanimously, any of us must actively terminate the discussion by replying with only one line, which starts with a single word <INFO>, followed by our final product modality without any other words, e.g., "<INFO> PowerPoint".

Traceback (most recent call last):
  File "C:\Users\stipi\anaconda3\envs\ChatDev_conda_env\lib\site-packages\tenacity\__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "C:\Users\stipi\chatdev\camel\utils.py", line 147, in wrapper
    raise ValueError('OpenAI API key not found.')
ValueError: OpenAI API key not found.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\stipi\chatdev\run.py", line 111, in <module>
    chat_chain.execute_chain()
  File "C:\Users\stipi\chatdev\chatdev\chat_chain.py", line 160, in execute_chain
    self.execute_step(phase_item)
  File "C:\Users\stipi\chatdev\chatdev\chat_chain.py", line 130, in execute_step
    self.chat_env = self.phases[phase].execute(self.chat_env,
  File "C:\Users\stipi\chatdev\chatdev\phase.py", line 292, in execute
    self.chatting(chat_env=chat_env,
  File "C:\Users\stipi\chatdev\chatdev\utils.py", line 77, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\stipi\chatdev\chatdev\phase.py", line 131, in chatting
    assistant_response, user_response = role_play_session.step(input_user_msg, chat_turn_limit == 1)
  File "C:\Users\stipi\chatdev\camel\agents\role_playing.py", line 242, in step
    assistant_response = self.assistant_agent.step(user_msg_rst)
  File "C:\Users\stipi\anaconda3\envs\ChatDev_conda_env\lib\site-packages\tenacity\__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "C:\Users\stipi\anaconda3\envs\ChatDev_conda_env\lib\site-packages\tenacity\__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "C:\Users\stipi\anaconda3\envs\ChatDev_conda_env\lib\site-packages\tenacity\__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x167a1a7c7f0 state=finished raised ValueError>]

**Comment by stjema** [comment]
solved: dont put api between "___"

**Comment by stjema** [comment]
i take it back.... tried it again without "", doesnt work, same error
