### ISSUE TITLE
UnicodeEncodeError When trying to run app.

### ISSUE THREAD

**Issue by mudislandkid** [OpenBMB/ChatDev#106]
I've tried both custom and default CompanyConfigs with the same result each time. I can't trace any rogue "smart quotes". Any Ideas? Am running anaconda with python 3.9.18.

```
Traceback (most recent call last):
  File "/root/anaconda3/envs/ChatDev_conda_env/lib/python3.9/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/root/ChatDev/camel/utils.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "/root/ChatDev/camel/agents/chat_agent.py", line 191, in step
    response = self.model_backend.run(messages=openai_messages)
  File "/root/ChatDev/camel/model_backend.py", line 69, in run
    response = openai.ChatCompletion.create(*args, **kwargs,
  File "/root/anaconda3/envs/ChatDev_conda_env/lib/python3.9/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/root/anaconda3/envs/ChatDev_conda_env/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/root/anaconda3/envs/ChatDev_conda_env/lib/python3.9/site-packages/openai/api_requestor.py", line 288, in request
    result = self.request_raw(
  File "/root/anaconda3/envs/ChatDev_conda_env/lib/python3.9/site-packages/openai/api_requestor.py", line 596, in request_raw
    result = _thread_context.session.request(
  File "/root/anaconda3/envs/ChatDev_conda_env/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/anaconda3/envs/ChatDev_conda_env/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/root/anaconda3/envs/ChatDev_conda_env/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/root/anaconda3/envs/ChatDev_conda_env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/root/anaconda3/envs/ChatDev_conda_env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
  File "/root/anaconda3/envs/ChatDev_conda_env/lib/python3.9/site-packages/urllib3/connection.py", line 387, in request
    self.putheader(header, value)
  File "/root/anaconda3/envs/ChatDev_conda_env/lib/python3.9/site-packages/urllib3/connection.py", line 301, in putheader
    super().putheader(header, *values)
  File "/root/anaconda3/envs/ChatDev_conda_env/lib/python3.9/http/client.py", line 1258, in putheader
    values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode character '\u201c' in position 7: ordinal not in range(256)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/ChatDev/run.py", line 98, in <module>
    chat_chain.execute_chain()
  File "/root/ChatDev/chatdev/chat_chain.py", line 160, in execute_chain
    self.execute_step(phase_item)
  File "/root/ChatDev/chatdev/chat_chain.py", line 130, in execute_step
    self.chat_env = self.phases[phase].execute(self.chat_env,
  File "/root/ChatDev/chatdev/phase.py", line 292, in execute
    self.chatting(chat_env=chat_env,
  File "/root/ChatDev/chatdev/utils.py", line 77, in wrapper
    return func(*args, **kwargs)
  File "/root/ChatDev/chatdev/phase.py", line 131, in chatting
    assistant_response, user_response = role_play_session.step(input_user_msg, chat_turn_limit == 1)
  File "/root/ChatDev/camel/agents/role_playing.py", line 242, in step
    assistant_response = self.assistant_agent.step(user_msg_rst)
  File "/root/anaconda3/envs/ChatDev_conda_env/lib/python3.9/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/root/anaconda3/envs/ChatDev_conda_env/lib/python3.9/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/root/anaconda3/envs/ChatDev_conda_env/lib/python3.9/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7f4f6a01bf10 state=finished raised UnicodeEncodeError>]
```

**Comment by mudislandkid** [comment]
User Error - :/ 

The curly " were in my API key environment variable. In case anyone else comes across this.
