### ISSUE TITLE
Issue running -tenacity time out

### ISSUE THREAD

**Issue by shirtshack** [OpenBMB/ChatDev#119]
Sorry new to coding but I have tried multiple ways of setting my api key and always get the same error out put with tenacity time out- anybody spot anythging obvious I am doing wrong- using anaconda prompt on windows 11-

Traceback (most recent call last):
  File "C:\Users\info\.conda\envs\ChatDev_conda_env\lib\site-packages\tenacity\__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "C:\Users\info\ChatDev\camel\utils.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\info\ChatDev\camel\agents\chat_agent.py", line 191, in step
    response = self.model_backend.run(messages=openai_messages)
  File "C:\Users\info\ChatDev\camel\model_backend.py", line 69, in run
    response = openai.ChatCompletion.create(*args, **kwargs,
  File "C:\Users\info\.conda\envs\ChatDev_conda_env\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\Users\info\.conda\envs\ChatDev_conda_env\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "C:\Users\info\.conda\envs\ChatDev_conda_env\lib\site-packages\openai\api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "C:\Users\info\.conda\envs\ChatDev_conda_env\lib\site-packages\openai\api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\info\.conda\envs\ChatDev_conda_env\lib\site-packages\openai\api_requestor.py", line 763, in _interpret_response_line
    raise self.handle_error_response(
openai.error.AuthenticationError: Incorrect API key provided: "sk-sm1f*****************************************pRM". You can find your API key at https://platform.openai.com/account/api-keys.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\info\ChatDev\run.py", line 111, in <module>
    chat_chain.execute_chain()
  File "C:\Users\info\ChatDev\chatdev\chat_chain.py", line 160, in execute_chain
    self.execute_step(phase_item)
  File "C:\Users\info\ChatDev\chatdev\chat_chain.py", line 130, in execute_step
    self.chat_env = self.phases[phase].execute(self.chat_env,
  File "C:\Users\info\ChatDev\chatdev\phase.py", line 292, in execute
    self.chatting(chat_env=chat_env,
  File "C:\Users\info\ChatDev\chatdev\utils.py", line 77, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\info\ChatDev\chatdev\phase.py", line 131, in chatting
    assistant_response, user_response = role_play_session.step(input_user_msg, chat_turn_limit == 1)
  File "C:\Users\info\ChatDev\camel\agents\role_playing.py", line 242, in step
    assistant_response = self.assistant_agent.step(user_msg_rst)
  File "C:\Users\info\.conda\envs\ChatDev_conda_env\lib\site-packages\tenacity\__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "C:\Users\info\.conda\envs\ChatDev_conda_env\lib\site-packages\tenacity\__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "C:\Users\info\.conda\envs\ChatDev_conda_env\lib\site-packages\tenacity\__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x29b86e9db50 state=finished raised AuthenticationError>]

**Comment by v0ku** [comment]
I got exactly the same issue. No idea yet. Did you find out something new?

**Comment by BOB99889** [comment]
Hello , i got the same error and i resolved it by following this steps: 

1- Make sure your API key is coorect at https://platform.openai.com/account/api-keys
2- Try to clear your browser cache, sometimes browser dosent maintain the last api key
3- Add OPEN_API_KEY variable manually by going to **environment variable**  
add new environment variable in the Variable Name type : **OPENAI_API_KEY**
add in value your API KEY 

![Screenshot_1](https://github.com/OpenBMB/ChatDev/assets/120720478/db7c3baa-dffa-48d4-a5d7-33f798ccd85c)

**Comment by Simaregele** [comment]
> OPENAI_API_KEY

This works for me, but don't forget to restart the power shell

**Comment by Simaregele** [comment]
> Hello , i got the same error and i resolved it by following this steps:
> 
> 1- Make sure your API key is coorect at https://platform.openai.com/account/api-keys 2- Try to clear your browser cache, sometimes browser dosent maintain the last api key 3- Add OPEN_API_KEY variable manually by going to **environment variable** add new environment variable in the Variable Name type : **OPENAI_API_KEY** add in value your API KEY
> 
> That worked perfectly for me ![Screenshot_1](https://user-images.githubusercontent.com/120720478/272872750-db7c3baa-dffa-48d4-a5d7-33f798ccd85c.png)

That works for me too, but don't forget to restart the terminal
