### ISSUE TITLE
Customizied all the json in the Default, and the phase.py folder but getting error

### ISSUE THREAD

**Issue by Baldbutgold** [OpenBMB/ChatDev#142]
```
Traceback (most recent call last):
  File "C:\Users\baldbutgold.DESKTOP-SMDEMTB\ChatDev\run.py", line 80, in <module>
    chat_chain = ChatChain(config_path=config_path,
  File "C:\Users\baldbutgold.DESKTOP-SMDEMTB\ChatDev\chatdev\chat_chain.py", line 53, in __init__
    self.config_phase = json.load(file)
  File "C:\Users\baldbutgold.DESKTOP-SMDEMTB\anaconda3\envs\ChatDev_conda_env\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\baldbutgold.DESKTOP-SMDEMTB\anaconda3\envs\ChatDev_conda_env\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\baldbutgold.DESKTOP-SMDEMTB\anaconda3\envs\ChatDev_conda_env\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\baldbutgold.DESKTOP-SMDEMTB\anaconda3\envs\ChatDev_conda_env\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 15 column 402 (char 1398)
```

**Comment by thinkwee** [comment]
Based on the bug information it seems that a comma is missing at the end of line 15 in your PhaseConfig.json 
Please share your json files and phase.py if you still have problems.
