### ISSUE TITLE
Tenacity Module Not Found

### ISSUE THREAD

**Issue by PageZ948** [OpenBMB/ChatDev#155]
Hey Everyone, Im having an issue when running the run.py. Im getting a kick back when trying to import retry from tenacity. It saying module tenacity not found. I installed all the requirements before hand and when i manual install tenacity, it already shows as being installed.

What to do next?

**Comment by Explosmac** [comment]
I was having the same issues. Reinstalled everything in a path without blank spaces and it worked.

**Comment by bunnis** [comment]
@PageZ948  what was your issue? I followed the instructions and I'm running into the exact same error, what am I overlooking? My Path has no blanks

**Comment by Explosmac** [comment]
@bunnis are you using python 3.9 from the official web site? I tried using the MS Store version and it not worked too.

**Comment by bunnis** [comment]
I'm on ubuntu with oficial packages I guess
~/ChatDev$ python --version
Python 3.9.18

**Comment by Explosmac** [comment]
Guess you already seen it, but maybe https://github.com/OpenBMB/ChatDev/issues/30#issuecomment-1712935170 helps. I'm running it on windows

**Comment by bunnis** [comment]
Nice catch, however doesn't work for me. I tried to use the python from my conda env:
`(base) bunnis@devops:~$ which python
/home/bunnis/miniconda3/bin/python
(base) bunnis@devops:~$ conda activate ChatDev_conda_env
(ChatDev_conda_env) bunnis@devops:~$ cd ChatDev
(ChatDev_conda_env) bunnis@devops:~/ChatDev$ which python
/home/bunnis/miniconda3/envs/ChatDev_conda_env/bin/python
(ChatDev_conda_env) bunnis@devops:~/ChatDev$ /home/bunnis/miniconda3/envs/ChatDev_conda_env/bin/python run.py --task "test" --name "test" --model 'GPT_4_32K'
Traceback (most recent call last):
  File "/home/bunnis/ChatDev/run.py", line 19, in <module>
    from camel.typing import ModelType
  File "/home/bunnis/ChatDev/camel/__init__.py", line 14, in <module>
    import camel.agents
  File "/home/bunnis/ChatDev/camel/agents/__init__.py", line 15, in <module>
    from .chat_agent import ChatAgent
  File "/home/bunnis/ChatDev/camel/agents/chat_agent.py", line 17, in <module>
    from tenacity import retry
ModuleNotFoundError: No module named 'tenacity'
`

**Comment by Explosmac** [comment]
I forgot to mention that I was able to run it with PyCharm, not Anaconda.

**Comment by bunnis** [comment]
I'm using command line, so not really sure what the problem is. I leave my trace here from a fresh install:

```(base) bunnis@devops:~$ git clone https://github.com/OpenBMB/ChatDev.git
Cloning into 'ChatDev'...
remote: Enumerating objects: 923, done.
remote: Counting objects: 100% (459/459), done.
remote: Compressing objects: 100% (326/326), done.
remote: Total 923 (delta 199), reused 252 (delta 131), pack-reused 464
Receiving objects: 100% (923/923), 31.62 MiB | 4.89 MiB/s, done.
Resolving deltas: 100% (270/270), done.
(base) bunnis@devops:~$ conda create -n ChatDev_conda_env python=3.9 -y
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 23.5.2
  latest version: 23.9.0

Please update conda by running

    $ conda update -n base -c defaults conda

Or to minimize the number of packages updated during conda update use

     conda install conda=23.9.0



## Package Plan ##

  environment location: /home/bunnis/miniconda3/envs/ChatDev_conda_env

  added / updated specs:
    - python=3.9


The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  _openmp_mutex      pkgs/main/linux-64::_openmp_mutex-5.1-1_gnu
  ca-certificates    pkgs/main/linux-64::ca-certificates-2023.08.22-h06a4308_0
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.38-h1181459_1
  libffi             pkgs/main/linux-64::libffi-3.4.4-h6a678d5_0
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-11.2.0-h1234567_1
  libgomp            pkgs/main/linux-64::libgomp-11.2.0-h1234567_1
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-11.2.0-h1234567_1
  ncurses            pkgs/main/linux-64::ncurses-6.4-h6a678d5_0
  openssl            pkgs/main/linux-64::openssl-3.0.11-h7f8727e_2
  pip                pkgs/main/linux-64::pip-23.2.1-py39h06a4308_0
  python             pkgs/main/linux-64::python-3.9.18-h955ad1f_0
  readline           pkgs/main/linux-64::readline-8.2-h5eee18b_0
  setuptools         pkgs/main/linux-64::setuptools-68.0.0-py39h06a4308_0
  sqlite             pkgs/main/linux-64::sqlite-3.41.2-h5eee18b_0
  tk                 pkgs/main/linux-64::tk-8.6.12-h1ccaba5_0
  tzdata             pkgs/main/noarch::tzdata-2023c-h04d1e81_0
  wheel              pkgs/main/linux-64::wheel-0.41.2-py39h06a4308_0
  xz                 pkgs/main/linux-64::xz-5.4.2-h5eee18b_0
  zlib               pkgs/main/linux-64::zlib-1.2.13-h5eee18b_0



Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate ChatDev_conda_env
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) bunnis@devops:~$ conda activate ChatDev_conda_env
(ChatDev_conda_env) bunnis@devops:~$ cd ChatDev
(ChatDev_conda_env) bunnis@devops:~/ChatDev$ pip3 install -r requirements.txt
Requirement already satisfied: aiohttp==3.8.4 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (3.8.4)
Requirement already satisfied: aiosignal==1.3.1 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 2)) (1.3.1)
Requirement already satisfied: astroid==2.15.0 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 3)) (2.15.0)
Requirement already satisfied: async-timeout==4.0.2 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 4)) (4.0.2)
Requirement already satisfied: attrs==23.1.0 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 5)) (23.1.0)
Requirement already satisfied: autopep8==1.6.0 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 6)) (1.6.0)
Requirement already satisfied: bidict==0.22.1 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 7)) (0.22.1)
Requirement already satisfied: blinker==1.6.2 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 8)) (1.6.2)
Requirement already satisfied: certifi==2023.5.7 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 9)) (2023.5.7)
Requirement already satisfied: cfgv==3.3.1 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 10)) (3.3.1)
Requirement already satisfied: charset-normalizer==3.1.0 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 11)) (3.1.0)
Requirement already satisfied: click==8.1.6 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 12)) (8.1.6)
Requirement already satisfied: colorama==0.4.6 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 13)) (0.4.6)
Requirement already satisfied: dill==0.3.6 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 14)) (0.3.6)
Requirement already satisfied: distlib==0.3.6 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 15)) (0.3.6)
Requirement already satisfied: docstring-to-markdown==0.11 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 16)) (0.11)
Requirement already satisfied: filelock==3.12.2 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 17)) (3.12.2)
Requirement already satisfied: flake8==6.0.0 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 18)) (6.0.0)
Requirement already satisfied: Flask==2.3.2 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 19)) (2.3.2)
Requirement already satisfied: Flask-SocketIO==5.3.4 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 20)) (5.3.4)
Requirement already satisfied: frozenlist==1.3.3 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 21)) (1.3.3)
Requirement already satisfied: identify==2.5.24 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 22)) (2.5.24)
Requirement already satisfied: idna==3.4 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 23)) (3.4)
Requirement already satisfied: importlib-metadata==6.8.0 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 24)) (6.8.0)
Requirement already satisfied: install==1.3.5 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 25)) (1.3.5)
Requirement already satisfied: isort==5.12.0 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 26)) (5.12.0)
Requirement already satisfied: itsdangerous==2.1.2 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 27)) (2.1.2)
Requirement already satisfied: jedi==0.18.2 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 28)) (0.18.2)
Requirement already satisfied: jieba==0.42.1 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 29)) (0.42.1)
Requirement already satisfied: Jinja2==3.1.2 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 30)) (3.1.2)
Requirement already satisfied: lazy-object-proxy==1.9.0 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 31)) (1.9.0)
Requirement already satisfied: Markdown==3.4.4 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 32)) (3.4.4)
Requirement already satisfied: MarkupSafe==2.1.3 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 33)) (2.1.3)
Requirement already satisfied: mccabe==0.7.0 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 34)) (0.7.0)
Requirement already satisfied: multidict==6.0.4 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 35)) (6.0.4)
Requirement already satisfied: nodeenv==1.8.0 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 36)) (1.8.0)
Requirement already satisfied: numpy==1.24.3 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 37)) (1.24.3)
Requirement already satisfied: openai==0.27.8 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 38)) (0.27.8)
Requirement already satisfied: packaging==23.0 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 39)) (23.0)
Requirement already satisfied: parso==0.8.3 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 40)) (0.8.3)
Requirement already satisfied: Pillow==9.5.0 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 41)) (9.5.0)
Requirement already satisfied: platformdirs==3.5.3 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 42)) (3.5.3)
Requirement already satisfied: pluggy==1.2.0 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 43)) (1.2.0)
Requirement already satisfied: pre-commit==3.3.3 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 44)) (3.3.3)
Requirement already satisfied: pycodestyle==2.10.0 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 45)) (2.10.0)
Requirement already satisfied: pydocstyle==6.2.3 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 46)) (6.2.3)
Requirement already satisfied: pyflakes==3.0.1 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 47)) (3.0.1)
Requirement already satisfied: pygame==2.5.1 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 48)) (2.5.1)
Requirement already satisfied: pylint==2.17.0 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 49)) (2.17.0)
Requirement already satisfied: PySocks==1.7.1 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 50)) (1.7.1)
Requirement already satisfied: python-engineio==4.5.1 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 51)) (4.5.1)
Requirement already satisfied: python-lsp-jsonrpc==1.0.0 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 52)) (1.0.0)
Requirement already satisfied: python-lsp-server==1.7.1 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 53)) (1.7.1)
Requirement already satisfied: python-socketio==5.8.0 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 54)) (5.8.0)
Requirement already satisfied: pytoolconfig==1.2.5 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 55)) (1.2.5)
Requirement already satisfied: PyYAML==6.0 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 56)) (6.0)
Requirement already satisfied: regex==2023.6.3 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 57)) (2023.6.3)
Requirement already satisfied: requests==2.31.0 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 58)) (2.31.0)
Requirement already satisfied: retrying==1.3.4 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 59)) (1.3.4)
Requirement already satisfied: rope==1.7.0 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 60)) (1.7.0)
Requirement already satisfied: six==1.16.0 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 61)) (1.16.0)
Requirement already satisfied: snowballstemmer==2.2.0 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 62)) (2.2.0)
Requirement already satisfied: tenacity==8.2.2 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 63)) (8.2.2)
Requirement already satisfied: tiktoken==0.4.0 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 64)) (0.4.0)
Requirement already satisfied: timeout-decorator==0.5.0 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 65)) (0.5.0)
Requirement already satisfied: toml==0.10.2 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 66)) (0.10.2)
Requirement already satisfied: tomli==2.0.1 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 67)) (2.0.1)
Requirement already satisfied: tomlkit==0.11.6 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 68)) (0.11.6)
Requirement already satisfied: tqdm==4.65.0 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 69)) (4.65.0)
Requirement already satisfied: typing_extensions==4.5.0 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 70)) (4.5.0)
Requirement already satisfied: ujson==5.7.0 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 71)) (5.7.0)
Requirement already satisfied: urllib3==2.0.3 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 72)) (2.0.3)
Requirement already satisfied: virtualenv==20.23.0 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 73)) (20.23.0)
Requirement already satisfied: Werkzeug==2.3.6 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 74)) (2.3.6)
Requirement already satisfied: whatthepatch==1.0.4 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 75)) (1.0.4)
Requirement already satisfied: wrapt==1.15.0 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 76)) (1.15.0)
Requirement already satisfied: yapf==0.32.0 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 77)) (0.32.0)
Requirement already satisfied: yarl==1.9.2 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 78)) (1.9.2)
Requirement already satisfied: zipp==3.16.2 in /home/bunnis/.local/lib/python3.8/site-packages (from -r requirements.txt (line 79)) (3.16.2)
Collecting retry==0.9.2
  Downloading retry-0.9.2-py2.py3-none-any.whl (8.0 kB)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from nodeenv==1.8.0->-r requirements.txt (line 36)) (45.2.0)
Collecting decorator>=3.4.2
  Downloading decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting py<2.0.0,>=1.4.26
  Downloading py-1.11.0-py2.py3-none-any.whl (98 kB)
     |████████████████████████████████| 98 kB 3.1 MB/s
Installing collected packages: decorator, py, retry
Successfully installed decorator-5.1.1 py-1.11.0 retry-0.9.2
(ChatDev_conda_env) bunnis@devops:~/ChatDev$ export OPENAI_API_KEY=""
(ChatDev_conda_env) bunnis@devops:~/ChatDev$ python3 run.py --task "test" --name "test" --model 'GPT_4_32K'
Traceback (most recent call last):
  File "/home/bunnis/ChatDev/run.py", line 19, in <module>
    from camel.typing import ModelType
  File "/home/bunnis/ChatDev/camel/__init__.py", line 14, in <module>
    import camel.agents
  File "/home/bunnis/ChatDev/camel/agents/__init__.py", line 15, in <module>
    from .chat_agent import ChatAgent
  File "/home/bunnis/ChatDev/camel/agents/chat_agent.py", line 17, in <module>
    from tenacity import retry
ModuleNotFoundError: No module named 'tenacity'
(ChatDev_conda_env) bunnis@devops:~/ChatDev$ python
Python 3.9.18 (main, Sep 11 2023, 13:41:44)
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tenacity
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tenacity'
>>>
(ChatDev_conda_env) bunnis@devops:~/ChatDev$ python --version
Python 3.9.18
(ChatDev_conda_env) bunnis@devops:~/ChatDev$ python run.py --task "test" --name "test" --model 'GPT_4_32K'
Traceback (most recent call last):
  File "/home/bunnis/ChatDev/run.py", line 19, in <module>
    from camel.typing import ModelType
  File "/home/bunnis/ChatDev/camel/__init__.py", line 14, in <module>
    import camel.agents
  File "/home/bunnis/ChatDev/camel/agents/__init__.py", line 15, in <module>
    from .chat_agent import ChatAgent
  File "/home/bunnis/ChatDev/camel/agents/chat_agent.py", line 17, in <module>
    from tenacity import retry
ModuleNotFoundError: No module named 'tenacity'
(ChatDev_conda_env) bunnis@devops:~/ChatDev$
(ChatDev_conda_env) bunnis@devops:~/ChatDev$ which python
/home/bunnis/miniconda3/envs/ChatDev_conda_env/bin/python
(ChatDev_conda_env) bunnis@devops:~/ChatDev$ /home/bunnis/miniconda3/envs/ChatDev_conda_env/bin/python run.py --task "test" --name "test" --model 'GPT_4_32K'
Traceback (most recent call last):
  File "/home/bunnis/ChatDev/run.py", line 19, in <module>
    from camel.typing import ModelType
  File "/home/bunnis/ChatDev/camel/__init__.py", line 14, in <module>
    import camel.agents
  File "/home/bunnis/ChatDev/camel/agents/__init__.py", line 15, in <module>
    from .chat_agent import ChatAgent
  File "/home/bunnis/ChatDev/camel/agents/chat_agent.py", line 17, in <module>
    from tenacity import retry
ModuleNotFoundError: No module named 'tenacity'
(ChatDev_conda_env) bunnis@devops:~/ChatDev$
```

**Comment by PageZ948** [comment]
Hey Everyone, I know ive been lacking on responding. If anyone was wondering, my issue was trying to use Conda from a command line on windows. Once you install Anaconda on windows, you should get a app call anaconda powershell prompt. Running the env from here and starting chatdev worked for me!

**Comment by JakeStrang1** [comment]
Got the same error on Ubuntu using Anaconda and python 3.11.

Fixed it by running `python -m pip install -r requirements` instead of `pip3 install -r requirements`. 🤷

**Comment by codingtmd** [comment]
> Got the same error on Ubuntu using Anaconda and python 3.11.
> 
> Fixed it by running `python -m pip install -r requirements.txt` instead of `pip3 install -r requirements.txt`. 🤷

This works for me as well.

**Comment by etonnelier** [comment]
Fixed if by opening a terminal instead of using the VSCode terminal.
