### ISSUE TITLE
ValueError("No Valid Codes.") during programmer phase

### ISSUE THREAD

**Issue by asjones-code** [OpenBMB/ChatDev#195]
I've been playing around with LM Studio + Mistral LLM with ChatDev with mixed results.

Once I was able to get some actual code written, but I'm now confronted with the above error. 

Is there some configuration I'm missing? Help!

**Comment by thinkwee** [comment]
Please provide the fall traceback.
Also, we haven't tried LM Studio and Mistral LLM. You can join our discord to see if any other people met and solved this problem. https://discord.com/invite/bn4t2Jy6TT

**Comment by alexdandrei** [comment]
Traceback (most recent call last):
  File "/mnt/77b8df50-bae6-4498-bdf5-5ce4201bb2b9/AI/chatdev/ChatDev/run.py", line 134, in <module>
    chat_chain.execute_chain()
  File "/mnt/77b8df50-bae6-4498-bdf5-5ce4201bb2b9/AI/chatdev/ChatDev/chatdev/chat_chain.py", line 166, in execute_chain
    self.execute_step(phase_item)
  File "/mnt/77b8df50-bae6-4498-bdf5-5ce4201bb2b9/AI/chatdev/ChatDev/chatdev/chat_chain.py", line 136, in execute_step
    self.chat_env = self.phases[phase].execute(self.chat_env,
  File "/mnt/77b8df50-bae6-4498-bdf5-5ce4201bb2b9/AI/chatdev/ChatDev/chatdev/phase.py", line 304, in execute
    chat_env = self.update_chat_env(chat_env)
  File "/mnt/77b8df50-bae6-4498-bdf5-5ce4201bb2b9/AI/chatdev/ChatDev/chatdev/phase.py", line 358, in update_chat_env
    raise ValueError("No Valid Codes.")
ValueError: No Valid Codes.


LM Studio + Openorca Platypus 2.
