### ISSUE TITLE
RuntimeError: Unexpected return from OpenAI API

### ISSUE THREAD

**Issue by gosadaque** [OpenBMB/ChatDev#264]
Hello everyone,

I've tried running ChatDev, but after 5 API requests it usually fails. It looks like its getting not the dict from the API as expected. I started tweaking around the code a bit, but this obv starts a waterfall of following functions which expect other forms of data.

Maybe someone else already experienced this and has a quick fix.

 Thanks in advance

```
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.9/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/home/ubuntu/ChatDev/camel/utils.py", line 147, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ubuntu/ChatDev/camel/agents/chat_agent.py", line 191, in step
    response = self.model_backend.run(messages=openai_messages)
  File "/home/ubuntu/ChatDev/camel/model_backend.py", line 88, in run
    raise RuntimeError("Unexpected return from OpenAI API")
RuntimeError: Unexpected return from OpenAI API

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/ChatDev/run.py", line 115, in <module>
    chat_chain.execute_chain()
  File "/home/ubuntu/ChatDev/chatdev/chat_chain.py", line 163, in execute_chain
    self.execute_step(phase_item)
  File "/home/ubuntu/ChatDev/chatdev/chat_chain.py", line 133, in execute_step
    self.chat_env = self.phases[phase].execute(self.chat_env,
  File "/home/ubuntu/ChatDev/chatdev/phase.py", line 291, in execute
    self.chatting(chat_env=chat_env,
  File "/home/ubuntu/ChatDev/chatdev/utils.py", line 77, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/ChatDev/chatdev/phase.py", line 130, in chatting
    assistant_response, user_response = role_play_session.step(input_user_msg, chat_turn_limit == 1)
  File "/home/ubuntu/ChatDev/camel/agents/role_playing.py", line 242, in step
    assistant_response = self.assistant_agent.step(user_msg_rst)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7fd3c6d1adf0 state=finished raised RuntimeError>]

```

**Comment by InfiniteCod3** [comment]
Got the same issue.

**Comment by kkazantz** [comment]
Same Here

**Comment by Charuru** [comment]
Same please fix

**Comment by alilkkanyil** [comment]
Same here as well, I don't see it in past issues, is this maybe caused by the most recent openai update?

**Comment by YuriGuernsey** [comment]
Anyone found a solution

**Comment by yoyomeme** [comment]
It's still working on my end but only work under --model GPT_3_5_TURBO

**Comment by fragilities** [comment]
same here. also can we add the 3.5 turbo 1106 to the model list?

**Comment by sineeeee** [comment]
same question, any new api key or model didn't work

**Comment by techclectic** [comment]
Having the same issue. Just installed this afternoon.

**Comment by Alphamasterliu** [comment]
Hello! Thank you very much for your feedback and reminder, it was detected to be a port version issue and we are now fixing this issue.

**Comment by Bu-Tianxing** [comment]
same problem again

**Comment by bigstrong1024** [comment]
28/02/2024,same problem again
