### ISSUE TITLE
AttributeError: module 'openai' has no attribute 'ChatCompletion'

### ISSUE THREAD

**Issue by InfiniteCod3** [OpenBMB/ChatDev#265]
Traceback (most recent call last):
  File "C:\Users\podpo\.conda\envs\chatdev\lib\site-packages\tenacity\__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "C:\Users\podpo\Desktop\ChatDev-main\ChatDev\camel\utils.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\podpo\Desktop\ChatDev-main\ChatDev\camel\agents\chat_agent.py", line 191, in step
    response = self.model_backend.run(messages=openai_messages)
  File "C:\Users\podpo\Desktop\ChatDev-main\ChatDev\camel\model_backend.py", line 70, in run
    response = openai.ChatCompletion.create(*args, **kwargs,
AttributeError: module 'openai' has no attribute 'ChatCompletion'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\podpo\Desktop\ChatDev-main\ChatDev\run.py", line 114, in <module>
    chat_chain.execute_chain()
  File "C:\Users\podpo\Desktop\ChatDev-main\ChatDev\chatdev\chat_chain.py", line 163, in execute_chain
    self.execute_step(phase_item)
  File "C:\Users\podpo\Desktop\ChatDev-main\ChatDev\chatdev\chat_chain.py", line 133, in execute_step
    self.chat_env = self.phases[phase].execute(self.chat_env,
  File "C:\Users\podpo\Desktop\ChatDev-main\ChatDev\chatdev\phase.py", line 291, in execute
    self.chatting(chat_env=chat_env,
  File "C:\Users\podpo\Desktop\ChatDev-main\ChatDev\chatdev\utils.py", line 77, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\podpo\Desktop\ChatDev-main\ChatDev\chatdev\phase.py", line 130, in chatting
    assistant_response, user_response = role_play_session.step(input_user_msg, chat_turn_limit == 1)
  File "C:\Users\podpo\Desktop\ChatDev-main\ChatDev\camel\agents\role_playing.py", line 242, in step
    assistant_response = self.assistant_agent.step(user_msg_rst)
  File "C:\Users\podpo\.conda\envs\chatdev\lib\site-packages\tenacity\__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "C:\Users\podpo\.conda\envs\chatdev\lib\site-packages\tenacity\__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "C:\Users\podpo\.conda\envs\chatdev\lib\site-packages\tenacity\__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x1e6f90f3dc0 state=finished raised AttributeError>]

**Comment by simtechcloud** [comment]
It should be openai.completions.create. as per Openai API defintion.

  (This one I recognize as a code suggestion flaw Openai often does ;-))

**Comment by howtobearealprogrammer** [comment]
is your version of `openai` pinned at 0.28.x? (or at least below 1.0.0)

`openai` 1.0.0 brought a huge change to how the API works and this caught me out the first time - namely because I tend to install everything, then update everything, then run... which then made errors galore.

**Comment by thinkwee** [comment]
we have updated the openapi. please pull the latest code and try again.
