### ISSUE TITLE
You are unable to access api.openai.com ?? 

### ISSUE THREAD

**Issue by 895268679long** [OpenBMB/ChatDev#276]
Traceback (most recent call last): File "/root/miniconda3/lib/python3.11/site-packages/openai/api_requestor.py", line 753, in _interpret_response_line data = json.loads(rbody) ^^^^^^^^^^^^^^^^^ File "/root/miniconda3/lib/python3.11/json/__init__.py", line 346, in loads return _default_decoder.decode(s) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/miniconda3/lib/python3.11/json/decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/miniconda3/lib/python3.11/json/decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0) The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/root/miniconda3/lib/python3.11/site-packages/tenacity/__init__.py", line 382, in __call__ result = fn(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^ File "/root/ChatDev/camel/utils.py", line 145, in wrapper return func(self, *args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/ChatDev/camel/agents/chat_agent.py", line 191, in step response = self.model_backend.run(messages=openai_messages) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/ChatDev/camel/model_backend.py", line 72, in run response = openai.ChatCompletion.create(*args, **kwargs, model=self.model_type.value, **self.model_config_dict) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/miniconda3/lib/python3.11/site-packages/openai/api_resources/chat_completion.py", line 25, in create return super().create(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/miniconda3/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create response, _, api_key = requestor.request( ^^^^^^^^^^^^^^^^^^ File "/root/miniconda3/lib/python3.11/site-packages/openai/api_requestor.py", line 298, in request resp, got_stream = self._interpret_response(result, stream) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/miniconda3/lib/python3.11/site-packages/openai/api_requestor.py", line 700, in _interpret_response self._interpret_response_line( File "/root/miniconda3/lib/python3.11/site-packages/openai/api_requestor.py", line 755, in _interpret_response_line raise error.APIError( openai.error.APIError: HTTP code 403 from API (
Please enable cookies.
Sorry, you have been blocked
You are unable to access api.openai.com
Why have I been blocked?
This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.

What can I do to resolve this?
You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page.

Cloudflare Ray ID: 8278bf091dc91061 • Your IP: Click to reveal 8.217.181.80 • Performance & security by [Cloudflare](https://www.cloudflare.com/5xx-error-landing)

)

**Comment by ror0ror02** [comment]
Use Vpn

**Comment by Alphamasterliu** [comment]
Hello,

When encountering issues with accessing api.base, it is important to check your network connection. For instance, verify if your location is within the regions authorized for OpenAI usage. In this case, I would suggest connecting to a VPN based in the United States and switching to a stable network connection or trying out a mobile hotspot. Thank you for your interest and efforts in trying out ChatDev! If you have any more questions or issues, please don't hesitate to raise them again. 😊
