### ISSUE TITLE
Custom Phase: Dictionary Referenced Before Assignment

### ISSUE THREAD

**Issue by bridgebrain** [OpenBMB/ChatDev#283]
I'm trying to build a researcher class to see if telling an agent to think over everything at every step will improve results. Right now though, I'm stuck altering phase.py, no matter what it seems to be breaking the dictionarys. I've tried a few different ways to program the agent, so if this isn't a functional setup that's understandable. It occurs if I just put in the code for the DemandAnalysis as well. 

Here is the error:
```
Traceback (most recent call last):
  File "C:\users\bridgebrain\documents\ai-core\chatdev\chatdev\run.py", line 102, in <module>
    chat_chain.pre_processing()
  File "C:\users\bridgebrain\documents\ai-core\chatdev\chatdev\chatdev\chat_chain.py", line 200, in pre_processing
    software_path = os.path.join(directory, "_".join([self.project_name, self.org_name, self.start_time]))
UnboundLocalError: local variable 'directory' referenced before assignment

```

And here's my agent class:
```
class Research(Phase):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    def update_phase_env(self, chat_env):
        self.phase_env.update({"task": chat_env.env_dict['task_prompt'],
                               "modality": chat_env.env_dict['modality'],
                               "ideas": chat_env.env_dict['ideas']})
  

    def update_chat_env(self, chat_env) -> ChatEnv:
        if len(self.seminar_conclusion) > 0 and "<INFO>" in self.seminar_conclusion:
            chat_env.env_dict['ideas'] = self.seminar_conclusion.split("<INFO>")[-1].lower().replace(".", "").strip()
        elif len(self.seminar_conclusion) > 0:
            chat_env.env_dict['ideas'] = self.seminar_conclusion
        else:
            chat_env.env_dict['ideas'] = "No new information"
        return chat_env

    def execute(self, chat_env, chat_turn_limit, need_reflect) -> ChatEnv:
        self.update_phase_env(chat_env)
        self.seminar_conclusion = \
            self.chatting(chat_env=chat_env,
                          task_prompt=chat_env.env_dict['task_prompt'],
                          need_reflect=need_reflect,
                          assistant_role_name=self.assistant_role_name,
                          user_role_name=self.user_role_name,
                          phase_prompt=self.phase_prompt,
                          phase_name=self.phase_name,
                          assistant_role_prompt=self.assistant_role_prompt,
                          user_role_prompt=self.user_role_prompt,
                          chat_turn_limit=chat_turn_limit,
                          placeholders=self.phase_env,
                          model_type=self.model_type)
        chat_env = self.update_chat_env(chat_env)
        return chat_env

```

**Comment by thinkwee** [comment]
it seems like the "clear_structure" is set to False in the ChatChainConfig.json, and we did not initialize the directory when clear_structure is False. you can set clear_structure to True and we will improve the code as well
