### ISSUE TITLE
It crashed in the middle of building the app

### ISSUE THREAD

**Issue by ilearnio** [OpenBMB/ChatDev#300]
It was running for about 2 minutes and then crashed with error, thought you may want to have a look

```
python run.py --name=crypto-coins-scanner --model=GPT_4 --task='...'

FILENAME
```LANGUAGE
'''
DOCSTRING
'''
CODE
\`\`\`
As the Programmer, to satisfy the new user's demand and make the software creative, executive and robust, you should modify corresponding codes according to the comments. Then, output the full and complete codes with all bugs fixed based on the comments. Return all codes strictly following the required format.

Traceback (most recent call last):
  File "/Users/admin/code/tmp/ChatDev/run.py", line 114, in <module>
    chat_chain.execute_chain()
  File "/Users/admin/code/tmp/ChatDev/chatdev/chat_chain.py", line 163, in execute_chain
    self.execute_step(phase_item)
  File "/Users/admin/code/tmp/ChatDev/chatdev/chat_chain.py", line 152, in execute_step
    self.chat_env = compose_phase_instance.execute(self.chat_env)
  File "/Users/admin/code/tmp/ChatDev/chatdev/composed_phase.py", line 152, in execute
    chat_env = self.phases[phase].execute(chat_env,
  File "/Users/admin/code/tmp/ChatDev/chatdev/phase.py", line 291, in execute
    self.chatting(chat_env=chat_env,
  File "/Users/admin/code/tmp/ChatDev/chatdev/utils.py", line 77, in wrapper
    return func(*args, **kwargs)
  File "/Users/admin/code/tmp/ChatDev/chatdev/phase.py", line 136, in chatting
    if isinstance(assistant_response.msg, ChatMessage):
  File "/Users/admin/code/tmp/ChatDev/camel/agents/chat_agent.py", line 53, in msg
    raise RuntimeError("error in ChatAgentResponse, info:{}".format(str(self.info)))
RuntimeError: error in ChatAgentResponse, info:{'id': None, 'usage': None, 'termination_reasons': ['max_tokens_exceeded_by_camel'], 'num_tokens': 9661}
```

**Comment by ilearnio** [comment]
It turns out gpt4 limit exceeded, closing
