### ISSUE TITLE
ImportError: cannot import name 'log_and_print_online' from 'chatdev.utils'

### ISSUE THREAD

**Issue by bgagandeep** [OpenBMB/ChatDev#308]
Running this code on windows and when running the run.py script, getting the following error:

```
python run.py --task "design a 2048 game" --name "2048"  --org "THUNLP" --config "Default"

Traceback (most recent call last):
  File "c:\Users\bgaga\Documents\Python Scripts\chatdev\ChatDev\run.py", line 19, in <module>
    from camel.typing import ModelType
  File "c:\Users\bgaga\Documents\Python Scripts\chatdev\ChatDev\camel\__init__.py", line 14, in <module>
    import camel.agents
  File "c:\Users\bgaga\Documents\Python Scripts\chatdev\ChatDev\camel\agents\__init__.py", line 15, in <module>
    from .chat_agent import ChatAgent
  File "c:\Users\bgaga\Documents\Python Scripts\chatdev\ChatDev\camel\agents\chat_agent.py", line 24, in <module>
    from camel.model_backend import ModelBackend, ModelFactory
  File "c:\Users\bgaga\Documents\Python Scripts\chatdev\ChatDev\camel\model_backend.py", line 22, in <module>
    from chatdev.utils import log_and_print_online
ImportError: cannot import name 'log_and_print_online' from 'chatdev.utils' (c:\Users\bgaga\Documents\Python Scripts\chatdev\ChatDev\chatdev\utils.py)

```

Searched a bit and seems that the log_and_print_online function is missing from the utils.py file. 

Any suggestions?

**Comment by juxhinr** [comment]
same

**Comment by sonmat** [comment]
It appears that the function "log_and_print_online" in the file "chatdev.utils" has been renamed to "log_visualize" in the latest commit. Replacing "log_and_print_online" with "log_visualize" within the file "camel/model_backend.py" should resolve the issue.

**Comment by thinkwee** [comment]
sorry, we have fixed it. please clone the latest code and try again.

**Comment by remotecontrolmedia** [comment]
Thank you

**Comment by bgagandeep** [comment]
Fantastic it worked! Thank you!
