### ISSUE TITLE
error No module named 'bs4'

### ISSUE THREAD

**Issue by alexonbstudio** [OpenBMB/ChatDev#322]
Traceback (most recent call last):
  File "/Users/alexonbstudio/ChatDev/run.py", line 24, in <module>
    from chatdev.chat_chain import ChatChain
  File "/Users/alexonbstudio/ChatDev/chatdev/chat_chain.py", line 14, in <module>
    from camel.web_spider import modal_trans
  File "/Users/alexonbstudio/ChatDev/camel/web_spider.py", line 2, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'

**Comment by alexonbstudio** [comment]
after install pip3 install BeautifulSoup4
