### ISSUE TITLE
`TypeError: 'type' object is not subscriptable` in `run.py`

### ISSUE THREAD

**Issue by hemangjoshi37a** [OpenBMB/ChatDev#34]
Command I ran : 
```
python3 run.py --task "I want to create a buying/selling website like OLX and quickr but the main differentiator factor between them and us is that we want to have easier product listing process that uses AI/ML on each step to make the process more intuitive and easy to use for the user. for example we want to have a camera video firstly to detect what products are available in the video the seller is shooting to the by object detection, after that we want to do image segmentation of each oject that is present in the  video , then we want to use LLM to list to possible list of parameters of the specification of the detected object for each object, then if a particular parameter of the specifications is detectable from the video we can add value of that parameter but the remaining parameters can be added by having a step by step conversation with the user about the detected object, Now here we want to add new functionality in this that is adding a geolocation tagging for each object, for example we can add longitude and latitude data to each object's specification.  then we store the video clip and the specification data in appropriate format in our server. then once the user has done this for all required objects the listed objects will show in the user's dashboard , the listed items by the user. after that there is a edit and mark-as-sold button from which the user can edit the specifications and delete a product or  mark as sold. then we want to also use the nerf technology to display 3d of the detected object. We also want to have this phenomenon in our webapp that is flipping, which means if you want to buy something and someone else wants to sell something that matches the value than you can directly flip the things without exchanging money . we also want to enhance continuesly the specifications of the object based on the conversation of the seller with the buyers, for example if he mentions something that is not present in the current list of the specifications then there should be alert to add  that as new parameter of the specification.create a python backend and html frontend file for this . consider that we want to use PostgreSQL for storing the data for this application . consider here that we want to have user permission for location and camera sensor using appropriate prompt. once the user accepts the permissions then the page shown the video feed from the camera in the html below which a record button is available from which user can start stop recording the video on completion of the recording of the video it is sent back to the python backend which will save it with appropriate name and at appropriate location . we also want to save the location data of this from user location to our postgresql database. I want to show the submit button only when the video is recorded. also start and stop video recording button should display alternatively , for example if the user has not started recording the video yet then there should be a  start video recording button, if the video recording is on then there should be a stop video recording button, and then once the stop video recording is pressed then there should be submit button. once the video is submitted then it should be saved on the backend and the backend should run object detection algorith using pretrained huggingface model faster_rcnn_R_50_FPN_3x and return the result to the html which later will show this results below the record button." --name "Flippers"
```

Error I got : 
```
Traceback (most recent call last):
  File "run.py", line 24, in <module>
    from chatdev.chat_chain import ChatChain
  File "/home/hemang/Documents/GitHub/ChatDev/chatdev/chat_chain.py", line 12, in <module>
    from chatdev.chat_env import ChatEnv, ChatEnvConfig
  File "/home/hemang/Documents/GitHub/ChatDev/chatdev/chat_env.py", line 35, in <module>
    class ChatEnv:
  File "/home/hemang/Documents/GitHub/ChatDev/chatdev/chat_env.py", line 82, in ChatEnv
    def exist_bugs(self) -> tuple[bool, str]:
TypeError: 'type' object is not subscriptable
```

**Comment by Nbtguyoriginal** [comment]
Show the changed files like chat chain and any other changes made

Consider re pulling the repo and running the same command with standard
setting to see if the behavior persists

**Comment by Nbtguyoriginal** [comment]
Or consider using pybonce if your unsure where the error is or what's causing it 

https://github.com/Nbtguyoriginal/Pybonce
It's a simple gui based app for tracing errors and finding improvement areas 
Also has the ability to be adjusted for diffrent Size code bases with built in rate limiting

**Comment by shiftbug** [comment]
Check your Python version.  python --version
must be at least 3.9

**Comment by lijiahao2022** [comment]
Thank you for your feedback. Please make sure your python version is at least 3.9

Restart the current environment and check the Python version after the operation.
