### ISSUE TITLE
No module named 'tenacity'

### ISSUE THREAD

**Issue by SanketBaviskar** [OpenBMB/ChatDev#365]
Traceback (most recent call last):
  File "F:\Projects\ChatDev\run.py", line 19, in <module>
    from camel.typing import ModelType
  File "F:\Projects\ChatDev\camel\__init__.py", line 14, in <module>
    import camel.agents
  File "F:\Projects\ChatDev\camel\agents\__init__.py", line 15, in <module>     
    from .chat_agent import ChatAgent
  File "F:\Projects\ChatDev\camel\agents\chat_agent.py", line 17, in <module>   
    from tenacity import retry
ModuleNotFoundError: No module named 'tenacity'

I got this error not sure what to do

**Comment by NA-Wen** [comment]
It seems there might be an issue with your environment configuration. To resolve this, consider running `pip install -r requirements.txt` (for Windows) or` pip3 install -r requirements.txt` (for macOS or Linux) to install all the necessary packages. This command will ensure that your environment is properly set up with the required dependencies. For detailed instructions on setting up your environment, you can refer to our [tutorial](https://github.com/OpenBMB/ChatDev/blob/main/README.md#%EF%B8%8F-quickstart-with-terminal).
