### ISSUE TITLE
error running 

### ISSUE THREAD

**Issue by winos** [OpenBMB/ChatDev#396]
Hi, actually ii try test the tool, but when i running the console show it:

**command**
`python3` run.py --task "test a agency tech" --name "flash"

Traceback (most recent call last):
  File "run.py", line 24, in <module>
    from chatdev.chat_chain import ChatChain
  File "/home/ChatDev/chatdev/chat_chain.py", line 12, in <module>
    from chatdev.chat_env import ChatEnv, ChatEnvConfig
  File "/home/ChatDev/chatdev/chat_env.py", line 52, in <module>
    class ChatEnv:
  File "/home/ChatDev/chatdev/chat_env.py", line 107, in ChatEnv
    def exist_bugs(self) -> tuple[bool, str]:
TypeError: 'type' object is not subscriptable

what do i do?

**Comment by shiowen** [comment]
The specific error in your traceback is related to using **tuple[bool, str]**, which is a feature of Python 3.9 and later. If you are using an earlier version of Python, this syntax will not work.

You can fix it by trying to **upgrade to Python 3.9 or later version**
