### ISSUE TITLE
Cant get chatdev to work getting this error which appears to show i have exceeded my limit when i never have gone over

### ISSUE THREAD

**Issue by taynothing** [OpenBMB/ChatDev#440]
i want to use chatdev to help me make a program for the playstore that will use firebase with google sso is that even possible to do, chatgpt code messes up havent tried claude 3.* thought i would try chatdev to see if it would work and im getting this error Note that we must ONLY discuss the product modality and do not discuss anything else! Once we all have expressed our opinion(s) and agree with the results of the discussion unanimously, any of us must actively terminate the discussion by replying with only one line, which starts with a single word <INFO>, followed by our final product modality without any other words, e.g., "<INFO> PowerPoint".

Traceback (most recent call last):
  File "C:\Users\caznothing\ChatDev\ChatDev_env\Lib\site-packages\tenacity\__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\caznothing\ChatDev\camel\utils.py", line 154, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\caznothing\ChatDev\camel\agents\chat_agent.py", line 239, in step
    response = self.model_backend.run(messages=openai_messages)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\caznothing\ChatDev\camel\model_backend.py", line 99, in run
    response = client.chat.completions.create(*args, **kwargs, model=self.model_type.value,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\caznothing\ChatDev\ChatDev_env\Lib\site-packages\openai\_utils\_utils.py", line 299, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\caznothing\ChatDev\ChatDev_env\Lib\site-packages\openai\resources\chat\completions.py", line 598, in create
    return self._post(
           ^^^^^^^^^^^
  File "C:\Users\caznothing\ChatDev\ChatDev_env\Lib\site-packages\openai\_base_client.py", line 1055, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\caznothing\ChatDev\ChatDev_env\Lib\site-packages\openai\_base_client.py", line 834, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\Users\caznothing\ChatDev\ChatDev_env\Lib\site-packages\openai\_base_client.py", line 865, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\caznothing\ChatDev\ChatDev_env\Lib\site-packages\openai\_base_client.py", line 925, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\Users\caznothing\ChatDev\ChatDev_env\Lib\site-packages\openai\_base_client.py", line 865, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\caznothing\ChatDev\ChatDev_env\Lib\site-packages\openai\_base_client.py", line 925, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\Users\caznothing\ChatDev\ChatDev_env\Lib\site-packages\openai\_base_client.py", line 877, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\caznothing\ChatDev\run.py", line 134, in <module>
    chat_chain.execute_chain()
  File "C:\Users\caznothing\ChatDev\chatdev\chat_chain.py", line 168, in execute_chain
    self.execute_step(phase_item)
  File "C:\Users\caznothing\ChatDev\chatdev\chat_chain.py", line 138, in execute_step
    self.chat_env = self.phases[phase].execute(self.chat_env,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\caznothing\ChatDev\chatdev\phase.py", line 295, in execute
    self.chatting(chat_env=chat_env,
  File "C:\Users\caznothing\ChatDev\chatdev\utils.py", line 79, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\caznothing\ChatDev\chatdev\phase.py", line 133, in chatting
    assistant_response, user_response = role_play_session.step(input_user_msg, chat_turn_limit == 1)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\caznothing\ChatDev\camel\agents\role_playing.py", line 247, in step
    assistant_response = self.assistant_agent.step(user_msg_rst)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\caznothing\ChatDev\ChatDev_env\Lib\site-packages\tenacity\__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\caznothing\ChatDev\ChatDev_env\Lib\site-packages\tenacity\__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\caznothing\ChatDev\ChatDev_env\Lib\site-packages\tenacity\__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x1bdfda35650 state=finished raised RateLimitError>]

(ChatDev_env) C:\Users\caznothing\ChatDev>

i tried everything including changing the verisions of chatgpt and nothing works anyone have any ideas? and is chatdev even all that impressive is it worth the time to try to fix this issue? IS there anything else that can assist a complete novice at programming an app?

**Comment by zhanghb18** [comment]
According to the error content: openai.RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. 
This indicates that the bill balance of your openai account is insufficient and has exceeded the API usage limit. This is not a problem with chatdev. You can check your openai account.
