### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'audio'

### ISSUE THREAD

**Issue by yswami** [OpenBMB/ChatDev#465]
`Traceback (most recent call last):
  File "/Users/user/miniconda3/envs/ChatDev_conda_env/lib/python3.9/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/Users/user/Desktop/Trials/ChatDev/camel/utils.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/user/Desktop/Trials/ChatDev/camel/agents/chat_agent.py", line 243, in step
    output_messages = [
  File "/Users/user/Desktop/Trials/ChatDev/camel/agents/chat_agent.py", line 244, in <listcomp>
    ChatMessage(role_name=self.role_name, role_type=self.role_type,
TypeError: __init__() got an unexpected keyword argument 'audio'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/user/Desktop/Trials/ChatDev/run.py", line 136, in <module>
    chat_chain.execute_chain()
  File "/Users/user/Desktop/Trials/ChatDev/chatdev/chat_chain.py", line 168, in execute_chain
    self.execute_step(phase_item)
  File "/Users/user/Desktop/Trials/ChatDev/chatdev/chat_chain.py", line 138, in execute_step
    self.chat_env = self.phases[phase].execute(self.chat_env,
  File "/Users/user/Desktop/Trials/ChatDev/chatdev/phase.py", line 295, in execute
    self.chatting(chat_env=chat_env,
  File "/Users/user/Desktop/Trials/ChatDev/chatdev/utils.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "/Users/user/Desktop/Trials/ChatDev/chatdev/phase.py", line 133, in chatting
    assistant_response, user_response = role_play_session.step(input_user_msg, chat_turn_limit == 1)
  File "/Users/user/Desktop/Trials/ChatDev/camel/agents/role_playing.py", line 247, in step
    assistant_response = self.assistant_agent.step(user_msg_rst)
  File "/Users/user/miniconda3/envs/ChatDev_conda_env/lib/python3.9/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/Users/user/miniconda3/envs/ChatDev_conda_env/lib/python3.9/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/Users/user/miniconda3/envs/ChatDev_conda_env/lib/python3.9/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x112641fa0 state=finished raised TypeError>]`

**Comment by AhsanRiyad** [comment]
I am also getting same error.

**Comment by Noelle1831-k** [comment]
Same error too.

**Comment by thinkwee** [comment]
We have fixed it. Please pull the latest version, see https://github.com/OpenBMB/ChatDev/pull/466

**Comment by Guava1123** [comment]
@thinkwee this error is still present in MacNet branch v1.1.6

`[2025-01-20 20:02:14    graph.py]
Node 0 is optimizing
---

[2025-01-20 20:02:27    _client.py]
HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
---

[2025-01-20 20:02:46    _client.py]
HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
---

[2025-01-20 20:03:04    _client.py]
HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
---

[2025-01-20 20:03:23    _client.py]
HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
---

[2025-01-20 20:03:43    _client.py]
HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
---

Traceback (most recent call last):
  File "C:\Users\niels\MiniConda3\envs\Chatdev_Macnet\lib\site-packages\tenacity\__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "E:\ChatDev_Updated\camel\utils.py", line 160, in wrapper
    return func(self, *args, **kwargs)
  File "E:\ChatDev_Updated\camel\agents\chat_agent.py", line 244, in step
    output_messages = [
  File "E:\ChatDev_Updated\camel\agents\chat_agent.py", line 245, in <listcomp>
    ChatMessage(role_name=self.role_name, role_type=self.role_type,
TypeError: __init__() got an unexpected keyword argument 'audio'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\ChatDev_Updated\run.py", line 35, in <module>
    main()
  File "E:\ChatDev_Updated\run.py", line 27, in main
    graph.execute(args.task, args.name)
  File "E:\ChatDev_Updated\graph.py", line 342, in execute
    response, optimized_solution, suggestion = next_node.optimize(task_prompt=prompt,
  File "E:\ChatDev_Updated\graph.py", line 174, in optimize
    response = self.create_agent(self.system_message, "assistant").step(message).msgs[0].content
  File "C:\Users\niels\MiniConda3\envs\Chatdev_Macnet\lib\site-packages\tenacity\__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "C:\Users\niels\MiniConda3\envs\Chatdev_Macnet\lib\site-packages\tenacity\__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "C:\Users\niels\MiniConda3\envs\Chatdev_Macnet\lib\site-packages\tenacity\__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x28bff487490 state=finished raised TypeError>]

(Chatdev_Macnet) E:\ChatDev_Updated>`
