### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'proxies'

### ISSUE THREAD

**Issue by venkatesh3007** [OpenBMB/ChatDev#467]
Traceback (most recent call last):
  File "/home/dell/stealth/ChatDev/run.py", line 24, in <module>
    from chatdev.chat_chain import ChatChain
  File "/home/dell/stealth/ChatDev/chatdev/chat_chain.py", line 14, in <module>
    from camel.web_spider import modal_trans
  File "/home/dell/stealth/ChatDev/camel/web_spider.py", line 18, in <module>
    client = openai.OpenAI(
  File "/home/dell/anaconda3/envs/stealth_env_1/lib/python3.9/site-packages/openai/_client.py", line 107, in __init__
    super().__init__(
  File "/home/dell/anaconda3/envs/stealth_env_1/lib/python3.9/site-packages/openai/_base_client.py", line 738, in __init__
    self._client = http_client or httpx.Client(
TypeError: __init__() got an unexpected keyword argument 'proxies

getting this error now even the latest branch.

**Comment by kagomee** [comment]
In my case, I resolved the issue by running `pip install --upgrade openai`

**Comment by venkatesh3007** [comment]
thanks. worked
