### ISSUE TITLE
Issue with tasks

### ISSUE THREAD

**Issue by BoomChakal** [OpenBMB/ChatDev#61]
Hi,

I get an error when running a task. Any idea how to fix it?

==>
"
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/andreas/Documents/GitHub/ChatDev/camel/utils.py", line 147, in wrapper
    raise ValueError('OpenAI API key not found.')
ValueError: OpenAI API key not found.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/andreas/Documents/GitHub/ChatDev/run.py", line 111, in <module>
    chat_chain.execute_chain()
  File "/Users/andreas/Documents/GitHub/ChatDev/chatdev/chat_chain.py", line 163, in execute_chain
    self.execute_step(phase_item)
  File "/Users/andreas/Documents/GitHub/ChatDev/chatdev/chat_chain.py", line 133, in execute_step
    self.chat_env = self.phases[phase].execute(self.chat_env,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andreas/Documents/GitHub/ChatDev/chatdev/phase.py", line 294, in execute
    self.chatting(chat_env=chat_env,
  File "/Users/andreas/Documents/GitHub/ChatDev/chatdev/utils.py", line 77, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andreas/Documents/GitHub/ChatDev/chatdev/phase.py", line 131, in chatting
    assistant_response, user_response = role_play_session.step(input_user_msg, chat_turn_limit == 1)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andreas/Documents/GitHub/ChatDev/camel/agents/role_playing.py", line 242, in step
    assistant_response = self.assistant_agent.step(user_msg_rst)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x117af3550 state=finished raised ValueError>]
"

Thanks in advance!

**Comment by NA-Wen** [comment]
In the error message you provided: `ValueError: OpenAI API key not found.` 
That means you need to set your own OpenAI API key, which needs to be exported as an environment variable. Replace "your_OpenAI_API_key" with your actual API key. Remember that this environment variable is session-specific, so you need to set it again if you open a new terminal session. 
On Unix/Linux:
`export OPENAI_API_KEY="your_OpenAI_API_key"`
On Windows :
`$env:OPENAI_API_KEY="your_OpenAI_API_key"`
