### ISSUE TITLE
How to set the proxy address to 127.0.0.1:7890?

### ISSUE THREAD

**Issue by heiheiheibj** [OpenBMB/ChatDev#71]
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\chatdev\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "D:\ProgramData\Anaconda3\envs\chatdev\lib\site-packages\urllib3\connectionpool.py", line 874, in urlopen
    return self.urlopen(
  File "D:\ProgramData\Anaconda3\envs\chatdev\lib\site-packages\urllib3\connectionpool.py", line 874, in urlopen
    return self.urlopen(
  File "D:\ProgramData\Anaconda3\envs\chatdev\lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "D:\ProgramData\Anaconda3\envs\chatdev\lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1007)')))

thanks

**Comment by yhyu13** [comment]
SSL error is more likly to be that OpenAI's cloudflare has blocked your proxy server ip. Most HongKong servers are blocked, try some other regions.

**Comment by heiheiheibj** [comment]
我用了新加坡、美帝、新西兰和小日子的代理都不行，OPENAI的官网也打不开，唉，作罢

**Comment by yanaex** [comment]
export socks_proxy=socks5://127.0.0.1:7890
