### ISSUE TITLE
Receive error on Step 4.

### ISSUE THREAD

**Issue by colinljy** [OpenBMB/ChatDev#84]
Hi, I was installing everything fine up till step 4 when trying to input my OpenAI Api key.

This is how the error shows after installing the requirement:
(ChatDev_conda_env) C:\Users\Colin\ChatDev>$env:OPENAI_API_KEY="I've correctly inserted the API key here, sk-..."
The filename, directory name, or volume label syntax is incorrect.

It shows the ... incorrect and I couldn't proceed from there. How do I resolve this?

**Comment by HaithamSwe** [comment]
If you're using windows try this `setx OPENAI_API_KEY your-key /M`

**Comment by colinljy** [comment]
Alright.

It doesn't work with the /M. ERROR: Access to the registry path is denied.

But when I removed it from the command it shows: SUCCESS: Specified value was saved.

But when I ran the command to create the product it shows this instead:
`Traceback (most recent call last):
  File "C:\Users\Colin\anaconda3\envs\ChatDev_conda_env\lib\site-packages\tenacity\__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "C:\Users\Colin\ChatDev\camel\utils.py", line 147, in wrapper
    raise ValueError('OpenAI API key not found.')
ValueError: OpenAI API key not found.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Colin\ChatDev\run.py", line 111, in <module>
    chat_chain.execute_chain()
  File "C:\Users\Colin\ChatDev\chatdev\chat_chain.py", line 163, in execute_chain
    self.execute_step(phase_item)
  File "C:\Users\Colin\ChatDev\chatdev\chat_chain.py", line 133, in execute_step
    self.chat_env = self.phases[phase].execute(self.chat_env,
  File "C:\Users\Colin\ChatDev\chatdev\phase.py", line 294, in execute
    self.chatting(chat_env=chat_env,
  File "C:\Users\Colin\ChatDev\chatdev\utils.py", line 77, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Colin\ChatDev\chatdev\phase.py", line 131, in chatting
    assistant_response, user_response = role_play_session.step(input_user_msg, chat_turn_limit == 1)
  File "C:\Users\Colin\ChatDev\camel\agents\role_playing.py", line 242, in step
    assistant_response = self.assistant_agent.step(user_msg_rst)
  File "C:\Users\Colin\anaconda3\envs\ChatDev_conda_env\lib\site-packages\tenacity\__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "C:\Users\Colin\anaconda3\envs\ChatDev_conda_env\lib\site-packages\tenacity\__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "C:\Users\Colin\anaconda3\envs\ChatDev_conda_env\lib\site-packages\tenacity\__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x2403591c8e0 state=finished raised ValueError>]`

**Comment by CronusXd** [comment]
i have same problem

**Comment by tronba** [comment]
On win 10 22H2, installing in c:\users\username\ChatDev
I've followed the Quickstart guide to the letter (even used the same conda name, and get 
(The filename, directory name, or volume label syntax is incorrect. when trying to run,)
$env:OPENAI_API_KEY="I'm sure my API key is valid and that there is money on it"
When I try the (setx OPENAI_API_KEY my API key /M) I also get the (Access to the registry path is denied error) as stated before.

**Comment by nazimboudeffa** [comment]
Just use `set OPENAI_API_KEY=abc123`

**Comment by Simaregele** [comment]
> Just use `set OPENAI_API_KEY=abc123`

This work for me)
